# Generated by Django 3.0.9 on 2020-08-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'verbose_name': '系统名称', 'verbose_name_plural': '系统设置-值'},
        ),
        migrations.AlterField(
            model_name='set',
            name='setname',
            field=models.CharField(max_length=64, verbose_name='系统名称'),
        ),
        migrations.AlterField(
            model_name='set',
            name='setvalue',
            field=models.CharField(max_length=200, verbose_name='系统设置-值'),
        ),
    ]
